# Generated by Django 4.2 on 2024-10-16 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0003_exceptionchannel_proxychannel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadonlyPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=140, unique=True)),
                ("text", models.TextField(default="")),
                ("rendered_text", models.TextField(blank=True, default="")),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Published")], default=0
                    ),
                ),
                ("custom_summary", models.TextField(default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("published", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.channel"
                    ),
                ),
            ],
            options={
                "ordering": ["published"],
                "abstract": False,
            },
        ),
    ]
